### ISSUE TITLE
 sino.scom.baseframe

### ISSUE THREAD

**Issue by Kersten007** [hesso-valais/scom#2]
Hi Hesso,
I'm a beginner of python and i like to use your scom library. 
But after installing the library and starting the sample I get the error:
Traceback (most recent call last):
  File "./xtender_version.py", line 14, in <module>
    from sino import scom
  File "/usr/local/lib/python3.7/dist-packages/sino/scom/__init__.py", line 14, in <module>
    from . import frame
  File "/usr/local/lib/python3.7/dist-packages/sino/scom/frame.py", line 6, in <module>
    from .baseframe import *
ModuleNotFoundError: No module named 'sino.scom.baseframe'

Any idea how i can fix it?
Thanks
Kersten

**Comment by boozo-unlimited** [comment]
Hi Kersten,
It seems that the packages were not correctly installed. Could you please tell me about the environment you are running the library?
- Operating System
- Python version

Thanks

**Comment by Kersten007** [comment]
Hi Hesso,
the os is : debian 10, fresh install
the python is: python3 V 3.7.3. , no virtual environment (do I need the venv ?)

Thanks

**Comment by boozo-unlimited** [comment]
All right. venv should not be necessary whereas I only work with it.

You may have the same problem mentioned in issue #1. I suggest to try the work arround mentioned [here](https://github.com/hesso-valais/scom/issues/1#issuecomment-499873653).

**Comment by Kersten007** [comment]
the work arround doesn't work ... but "pip3 install -I --no-cache-dir scom" fixed the problem

**Comment by boozo-unlimited** [comment]
Are you now able to communicate with the Xtender?

**Comment by EmanueleZanardo** [comment]
Hi, I have the same problem but I could not solve it with both methods (I am using a satinberry pi 4 model B)

**Comment by petrkr** [comment]
Did you compiled C so libraries ? 

mentioned in setup.py :) Littlebit tricky about place where to put important stuff to make it work

https://github.com/hesso-valais/scom/blob/d819292aa8627e0a66e106898684792d42b4a0c9/src/sino/scom/setup.py#L10
